name: CICD Wordpress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-18.04]
        php-versions: ['7.2']
        mysql-version: ['5.7']
        db_name: ['db_test']
        db_user: ['root']
        db_password: ["''"]
        db_host: ['localhost']
        wp_version: ['latest']

    steps:
    - uses: actions/checkout@v2

    # - name: Set up MySQL
    - uses: ankane/setup-mysql@v1
      with:
        mysql-version: ${{ matrix.mysql-version }}

    # - run: mysql --version
    # - run: mysql -e 'SELECT VERSION()'
    # - run: mysql -e 'SELECT CURRENT_USER()'
    # - run: mysql -e 'SELECT DATABASE()'
    # - run: mysql -e "SHOW VARIABLES LIKE 'socket'"
    # - run: mysqladmin create testdb2
    # - run: mysql -D testdb -e 'SELECT DATABASE()'

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug #optional, setup coverage driver

    - name: Composer install
      run: |
        composer install --optimize-autoloader --prefer-dist
    
    - name: Install PHPUnit
      run: |
        wget https://phar.phpunit.de/phpunit-7.5.9.phar
        chmod +x phpunit-7.5.9.phar
        sudo mv phpunit-7.5.9.phar /usr/local/bin/phpunit
        phpunit --version

    - name: Install WP Tests
      run: bash ./wp-content/plugins/sentius-map/bin/install-wp-tests.sh ${{ matrix.db_name }} ${{ matrix.db_user }} ${{ matrix.db_password }} ${{ matrix.db_host }} ${{ matrix.wp_version }}

    - name: phpunit wp-content/plugins/*
      run: |
        cd wp-content/plugins/sentius-map
        phpunit
