name: CICD Wordpress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-18.04]
        php-versions: ['7.3']
        mysql-version: ['5.7']
        db_name: ['testdb3']
        db_user: ['root']
        db_password: ["''"]
        db_host: ['localhost']
        wp_version: ['latest']

    steps:
    - uses: actions/checkout@v2

    # - name: Set up MySQL
    - uses: ankane/setup-mysql@v1
      with:
        mysql-version: ${{ matrix.mysql-version }}

    # - run: mysql --version
    # - run: mysql -e 'SELECT VERSION()'
    # - run: mysql -e 'SELECT CURRENT_USER()'
    # - run: mysql -e 'SELECT DATABASE()'
    # - run: mysql -e "SHOW VARIABLES LIKE 'socket'"
    # - run: mysqladmin create testdb2
    # - run: mysql -D testdb -e 'SELECT DATABASE()'

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: mbstring, intl #optional, setup extensions
        ini-values-csv: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
        coverage: xdebug #optional, setup coverage driver
        pecl: false #optional, setup PECL

    - name: Composer install
      run: |
        composer install --optimize-autoloader --prefer-dist
    
    - name: Install PHPUnit
      run: |
        wget https://phar.phpunit.de/phpunit-7.5.9.phar
        chmod +x phpunit-7.5.9.phar
        sudo mv phpunit-7.5.9.phar /usr/local/bin/phpunit

    - name: Install WP Tests
      run: bash ./wp-content/plugins/sentius-map/bin/install-wp-tests.sh ${{ matrix.db_name }} ${{ matrix.db_user }} ${{ matrix.db_password }} ${{ matrix.db_host }} ${{ matrix.wp_version }}

    - name: phpunit tests
      run: phpunit ./wp-content/plugins/sentius-map/tests/test-sample.php

    # # - name: Validate composer.json and composer.lock
    # #   run: composer validate --strict

    # # - name: Cache Composer packages
    # #   id: composer-cache
    # #   uses: actions/cache@v2
    # #   with:
    # #     path: vendor
    # #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
    # #     restore-keys: |
    # #       ${{ runner.os }}-php-

    # # - name: Install dependencies
    # #   run: composer install --prefer-dist --no-progress

    # # # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # # # Docs: https://getcomposer.org/doc/articles/scripts.md

    # # - name: Run test suite
    # #   run: composer run-script test
